### PR TITLE
Remove SPI user, add breakouts for audio, i2c, and row 6

### PR DESCRIPTION
**Pull request by freznel10**
I've made this branch with additional config changes which I've used for the modified Scylla.

1. Added a sixth row. The following pins are used for the matrix:

#define MATRIX_COL_PINS { B5, B4, B15, B14, A15, A8 }
#define MATRIX_ROW_PINS { B3, B6, B13, B12, A10, B7 }

2. Split hand pin is C14

#define SPLIT_HAND_PIN      C14

3. Audio pin is B1

#define AUDIO_PIN          B1
#define AUDIO_PWM_DRIVER   PWMD3
#define AUDIO_PWM_CHANNEL  4
#define AUDIO_PWM_PAL_MODE 2
#define AUDIO_STATE_TIMER  GPTD4

4. The TRRS footprints are now mapped to A3 and A2 for USART full duplex. They are switched on the two sides since the Blackpill does not support pinswap.

/* serial.c configuration for split keyboard */
#define SERIAL_USART_FULL_DUPLEX  // Enable full duplex operation mode.
#define SERIAL_USART_TX_PIN      A2
#define SERIAL_USART_RX_PIN      A3
#define SERIAL_USART_DRIVER      SD2
#define SERIAL_USART_TX_PAL_MODE 7    // Pin "alternate function", see the respective datasheet for the appropriate values for your MCU. default: 7
#define SERIAL_USART_RX_PAL_MODE 7    // Pin "alternate function", see the respective datasheet for the appropriate values for your MCU. default: 7
#define SERIAL_USART_TIMEOUT     100  // USART driver timeout. default 100

5. I2C pins have been broken out for oled use.

/* i2c config for oleds */
#define I2C_DRIVER        I2CD1
#define I2C1_SCL_PIN      B8
#define I2C1_SDA_PIN      B9
#define I2C1_SCL_PAL_MODE 4
#define I2C1_SDA_PAL_MODE 4
// #define I2C1_CLOCK_SPEED  400000
/* For Legacy Compatibility: */
#define I2C1_SCL 8
#define I2C1_SDA 9

6. Trackball CS pin has been remapped to B0

### CODE REVIEW

**Comment by bstiq** [comment]
Hey,

What's up with the changed mapping of the trackball pinout ?
I'd rather have it unchanged, as it would mean also changing the sensor PCBs.

**Comment by freznel10** [comment]
Hi Quentin,

This is an altogether different branch which closely follows drashna's
default config and mapping and is not meant to override the default adapter
PCB config. I've tested it with the Charybdis PCB and it works with the
config changes I made in the PR. I wanted to fit the available pins for
i2c, audio and a sixth row.

**Comment by bstiq** [comment]
Allright, makes sense.
I don't know what's the consensus on that, but might make sense to make it a fork instead ?

**Comment by freznel10** [comment]
Yeah, I think it could remain on my fork. Just putting it out there in case
somebody wants to build a customized/modde Charybdis with audio, oled
encoder and additional keys.

**Pull request closed without merging**
