### PR TITLE
WIP: Revision 1.2

### PR DESCRIPTION
**Pull request by KarlK90**

### CODE REVIEW

**Comment by bstiq** [comment]
@KarlK90 what's the best way to work both at the same time on this ? 
Make a new branch, open an issue ?
Eg. I want to increase the thermal relief gaps to make soldering pins to gnd headers easier.

**Comment by KarlK90** [comment]
Just push, I won't have time until tomorrow to do anything

**Comment by nstetter** [comment]
@KarlK90, what is the status of the 1.2 release? Have you stopped working on it?

**Comment by KarlK90** [comment]
@nstetter yes I have stopped working on this as the RP2040 based boards in pro micro form factor took over.

**Pull request closed without merging**
